development:
  adapter: postgresql
  encoding: unicode
  database: ShindigSheriff_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ShindigSheriff_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ShindigSheriff_production
  pool: 5
  host: localhost
